name: Sparkle Interactive
favicon: null
layout_spectrum: 0.8895447
typography_spectrum: 0.5101181
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6666ff'
    - '#ffccff'
    - '#ff00ff'
    - '#000000'
    - '#ff72ff'
  brandStrength: 0.4915669
  lightness: 0.7487352
  saturation: 1
  rhythmicContrast: 0.811973
purpose: []
